# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
  (?x)(
      ^var/ |
      ^LICENSE
  )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-yaml
      - id: check-executables-have-shebangs
      - id: detect-private-key
      - id: pretty-format-json
        args: ['--autofix', '--top-keys', '_README,_note']
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
